# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

version: "3.10"
services:
  sd_managerscript:
    build: .
    command:
      [
        "uvicorn",
        "--factory",
        "app.main:create_app",
        "--host",
        "0.0.0.0",
        "--reload"
      ]
    environment:

      AUTH_SERVER: "http://keycloak:8080/auth"

      MO_URL: "http://mo"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

    networks:
      - os2mo_default
    ports:
      - "8000:8000"
    volumes:
      - ./sd_managerscript:/opt/app/

networks:
  os2mo_default:
    external: true
