# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

services:
  sd_managerscript:
    build:
      context: .
    environment:
      FASTRAMQPI__LOG_LEVEL: "INFO"
      FASTRAMQPI__JSON_LOGS: "true"

      # OS2mo
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
      FASTRAMQPI__AUTH_REALM: "mo"
      FASTRAMQPI__DATABASE__USER: "fastramqpi"
      FASTRAMQPI__DATABASE__PASSWORD: "fastramqpi"
      FASTRAMQPI__DATABASE__HOST: "db"
      FASTRAMQPI__DATABASE__NAME: "fastramqpi"

      # Manager sync
      ROOT_UUID: "f06ee470-9f17-566f-acbe-e938112d46d9"
      MANAGER_TYPE_UUID: "83b47e9e-de81-432e-bf0b-4ad95cd18589"
      RESPONSIBILITY_UUID: "82188ee7-a5da-4f3c-bf52-434d9ce57a65"
      MANAGER_LEVEL_MAPPING: '{
        "N1": "Niveau 1",
        "N2": "Niveau 2",
        "N3": "Niveau 3",
        "N4": "Niveau 4",
        "N5": "Niveau 4",
        "N6": "Niveau 4",
        "N7": "Niveau 4",
        "N8": "Niveau 4"
      }'
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - default
      - os2mo_default
    volumes:
      - ./:/app/:ro

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "fastramqpi"
      POSTGRES_PASSWORD: "fastramqpi"
      POSTGRES_DB: "fastramqpi"
    networks:
      - os2mo_default

networks:
  os2mo_default:
    external: true
