# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import AsyncIterator
from uuid import UUID
from uuid import uuid4

import pytest
from asgi_lifespan import LifespanManager
from asgi_lifespan._types import ASGIApp
from fastapi import FastAPI
from httpx import ASGITransport
from httpx import AsyncClient
from pytest import MonkeyPatch

from sd_managerscript.autogenerated_graphql_client import GraphQLClient
from sd_managerscript.main import create_app


@pytest.fixture
def root_uuid():
    return uuid4()


@pytest.fixture()
def _app(monkeypatch: MonkeyPatch, root_uuid: UUID) -> FastAPI:
    monkeypatch.setenv("ROOT_UUID", str(root_uuid))
    monkeypatch.setenv("MANAGER_TYPE_UUID", "75fee2b6-f405-4c77-b62e-32421c2e43d5")
    monkeypatch.setenv("RESPONSIBILITY_UUID", "d82039a5-f2d5-48e4-8eab-8c9f7694e16f")
    monkeypatch.setenv(
        "MANAGER_LEVEL_MAPPING",
        """
            {
                "1ec3d3ae-8ad6-f689-57a9-7441f6ffca05": "9a2bbe63-b7b4-4b3d-9b47-9d7dd391b42c",
                "891603db-cc28-6ed2-6d48-25e14d3f142f": "e226821b-4af3-1e91-c53f-ea5c57c6d8d0",
                "0263522a-2c1e-9c80-1880-92c1b97cfead": "a8754726-a4b9-1715-6b41-769c6fe703c5",
                "fc968d00-41f2-3efb-401a-30a3cf854227": "9ffaff0f-8b6e-6e99-a517-f841a04c61c2",
                "750e734e-17b8-0174-6787-a5be55adca31": "9ffaff0f-8b6e-6e99-a517-f841a04c61c2",
                "3ee6f4a5-02cc-41a0-82cc-4b8243664423": "9ffaff0f-8b6e-6e99-a517-f841a04c61c2"
            }
        """,
    )
    app = create_app()
    return app


@pytest.fixture
async def asgiapp(_app: FastAPI) -> AsyncIterator[ASGIApp]:
    """ASGI app with lifespan run."""
    async with LifespanManager(_app) as manager:
        yield manager.app


@pytest.fixture
async def app(_app: FastAPI, asgiapp: ASGIApp) -> FastAPI:
    """FastAPI app with lifespan run."""
    return _app


@pytest.fixture
async def test_client(asgiapp: ASGIApp) -> AsyncIterator[AsyncClient]:
    """Create test client with associated lifecycles."""
    transport = ASGITransport(app=asgiapp, client=("1.2.3.4", 123))  # type: ignore
    async with AsyncClient(
        transport=transport, base_url="http://example.com"
    ) as client:
        yield client


@pytest.fixture
async def graphql_client(app: FastAPI) -> GraphQLClient:
    """Authenticated GraphQL codegen client for OS2mo."""
    return app.state.context["graphql_client"]
