# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import AsyncIterator
from uuid import UUID
from uuid import uuid4

import pytest
from asgi_lifespan import LifespanManager
from asgi_lifespan._types import ASGIApp
from fastapi import FastAPI
from httpx import ASGITransport
from httpx import AsyncClient
from pytest import MonkeyPatch

from sd_managerscript.autogenerated_graphql_client import GraphQLClient
from sd_managerscript.config import _Settings
from sd_managerscript.main import create_app

manager_level_mapping = {
    "418b313a-979f-4a26-807e-ba8dd3114d74": "97ab3d21-4b9d-420c-b738-fde6a56ffb45",
    "53350314-820e-4bcc-a286-b0c1bb7738e9": "9a2bbe63-b7b4-4b3d-9b47-9d7dd391b42c",
    "84f95e29-48a0-4175-85fd-84a1f596e1a4": "d09ba017-f838-4742-b57e-44c2f5437e38",
    "abbbefb2-85a6-4a5d-ad94-98a363adfee6": "f0a18e70-dcd1-4c42-9cb3-f9602fb25a69",
}


@pytest.fixture
def root_uuid():
    return uuid4()


@pytest.fixture()
def _app(monkeypatch: MonkeyPatch, root_uuid: UUID) -> FastAPI:
    monkeypatch.setenv("ROOT_UUID", str(root_uuid))
    monkeypatch.setenv("MANAGER_TYPE_UUID", "75fee2b6-f405-4c77-b62e-32421c2e43d5")
    monkeypatch.setenv("RESPONSIBILITY_UUID", "d82039a5-f2d5-48e4-8eab-8c9f7694e16f")
    monkeypatch.setenv("MANAGER_LEVEL_MAPPING", json.dumps(manager_level_mapping))
    app = create_app()
    return app


@pytest.fixture
async def asgiapp(_app: FastAPI) -> AsyncIterator[ASGIApp]:
    """ASGI app with lifespan run."""
    async with LifespanManager(_app) as manager:
        yield manager.app


@pytest.fixture
async def app(_app: FastAPI, asgiapp: ASGIApp) -> FastAPI:
    """FastAPI app with lifespan run."""
    return _app


@pytest.fixture
async def test_client(asgiapp: ASGIApp) -> AsyncIterator[AsyncClient]:
    """Create test client with associated lifecycles."""
    transport = ASGITransport(app=asgiapp, client=("1.2.3.4", 123))  # type: ignore
    async with AsyncClient(
        transport=transport, base_url="http://example.com"
    ) as client:
        yield client


@pytest.fixture
async def graphql_client(app: FastAPI) -> GraphQLClient:
    """Authenticated GraphQL codegen client for OS2mo."""
    return app.state.context["graphql_client"]


@pytest.fixture()
def settings(monkeypatch: MonkeyPatch, root_uuid: UUID) -> _Settings:
    monkeypatch.setenv("FASTRAMQPI__CLIENT_ID", "unused")
    monkeypatch.setenv("FASTRAMQPI__CLIENT_SECRET", "unused")
    monkeypatch.setenv("FASTRAMQPI__AMQP__URL", "amqp://unused")

    monkeypatch.setenv("ROOT_UUID", str(root_uuid))
    monkeypatch.setenv("MANAGER_TYPE_UUID", "75fee2b6-f405-4c77-b62e-32421c2e43d5")
    monkeypatch.setenv("RESPONSIBILITY_UUID", "d82039a5-f2d5-48e4-8eab-8c9f7694e16f")
    monkeypatch.setenv("MANAGER_LEVEL_MAPPING", json.dumps(manager_level_mapping))
    return _Settings()
