# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import pytest
from httpx import AsyncClient
from more_itertools import one

from sd_managerscript.autogenerated_graphql_client import GraphQLClient
from sd_managerscript.config import ManagerSyncSettings


@pytest.mark.integration_test
async def test_reconcile_leder_managers(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    settings: ManagerSyncSettings,
) -> None:
    """
    Integration test for trigger endpoint `/trigger/all`.

    Scenario:

        Root
        ├── Department A (led-adm)
        │   └── Team A1_leder
        ├── Department B
        │   └── Team B1_leder
        ├── Department C
        └── Department D
            └── Ø_Team D1_leder

    Explanation:

    - Department A (led-adm branch) has a child `_leder` unit `Team A1_leder`:
    - emp1 is associated with the `_leder` unit and has an active engagement in the parent led-adm unit (Department A led-adm).
    - Two managers are created:
        1. In the led-adm parent (Department A led-adm)
        2. In the parent of led-adm (Root)

    - Department B has a child `_leder` unit `Team B1_leder`:
    - emp2 is associated with the `_leder` unit and has an active engagement in the parent (Department B).
    - A manager is created for the parent unit (Department B).

    - Department C has no `_leder` unit:
    - emp3 is associated here.
    - No manager is created because only `_leder` units are considered.

    - Department D has a child `_leder` unit prefixed with `Ø_` (`Ø_Team D1_leder`):
    - emp4 is associated here and already has a manager.
    - This unit is excluded due to the `Ø_` prefix rule.
    - The existing manager is terminated because the unit is ignored.

    Expected Outcome:

    - Managers created: 3
    - Department A led-adm + Root: 2
    - Department B: 1
    - Managers terminated: 1 (emp4 in Ø_Team D1_leder)
    """

    # Arrange

    # Create org-tree
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )

    org_unit_level = (
        (await graphql_client._testing__get_org_unit_level()).objects[0].uuid
    )

    root = (
        await graphql_client._testing__create_org_unit(
            name="Root",
            parent=None,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_a_led_adm = (
        await graphql_client._testing__create_org_unit(
            name="Department A led-adm",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_b = (
        await graphql_client._testing__create_org_unit(
            name="Department B",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    team_a1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team A1_leder",
            parent=department_a_led_adm,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    team_b1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team B1_leder",
            parent=department_b,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_c = (
        await graphql_client._testing__create_org_unit(
            name="Department C",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid
    department_d = (
        await graphql_client._testing__create_org_unit(
            name="Department D",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid
    team_d1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Ø_Team D1_leder",
            parent=department_d,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    # Create employees
    emp1 = (await graphql_client._testing__create_employee("Emp", "One")).uuid
    emp2 = (await graphql_client._testing__create_employee("Emp", "Two")).uuid
    emp3 = (await graphql_client._testing__create_employee("Emp", "Three")).uuid
    emp4 = (await graphql_client._testing__create_employee("Emp", "Four")).uuid

    # Create associations
    association_type_uuid = (
        (await graphql_client._testing__get_association_type()).objects[0].uuid
    )

    await graphql_client._testing__create_association(
        team_a1_leder, emp1, association_type_uuid
    )
    await graphql_client._testing__create_association(
        team_b1_leder, emp2, association_type_uuid
    )
    await graphql_client._testing__create_association(
        department_c, emp3, association_type_uuid
    )
    await graphql_client._testing__create_association(
        team_d1_leder, emp4, association_type_uuid
    )

    engagement_type = (
        (await graphql_client._testing__get_engagement_type()).objects[0].uuid
    )

    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )

    await graphql_client._testing__create_engagement(
        department_a_led_adm,
        emp1,
        engagement_type,
        job_function.uuid,
    )

    await graphql_client._testing__create_engagement(
        department_b,
        emp2,
        engagement_type,
        job_function.uuid,
    )

    await graphql_client._testing__create_engagement(
        department_c,
        emp3,
        engagement_type,
        job_function.uuid,
    )

    await graphql_client._testing__create_engagement(
        department_d,
        emp4,
        engagement_type,
        job_function.uuid,
    )

    # Create manager for emp4 in Ø_-org
    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid

    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )
    await graphql_client._testing__create_manager(
        team_d1_leder, emp4, manager_level, manager_type, responsibility
    )

    # Act
    response = await test_client.post("/trigger/all")

    # Assert
    assert response.status_code == 202

    root_org_managers = await graphql_client._testing__get_org_unit_manager(root)
    root_manager = one(root_org_managers.objects)
    assert root_manager.current is not None
    assert root_manager.current.employee_uuid == emp1

    department_a_led_adm_org_managers = (
        await graphql_client._testing__get_org_unit_manager(department_a_led_adm)
    )
    department_a_manager = one(department_a_led_adm_org_managers.objects)
    assert department_a_manager.current is not None
    assert department_a_manager.current.employee_uuid == emp1

    department_b_org_managers = await graphql_client._testing__get_org_unit_manager(
        department_b
    )
    department_b_manager = one(department_b_org_managers.objects)
    assert department_b_manager.current is not None
    assert department_b_manager.current.employee_uuid == emp2

    all_current_managers = await graphql_client._testing__get_all_managers()
    assert len(all_current_managers.objects) == 3
