# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime

import pytest
from httpx import AsyncClient

from sd_managerscript.autogenerated_graphql_client import GraphQLClient
from sd_managerscript.config import _Settings
from sd_managerscript.mo import build_manager_mutation
from sd_managerscript.mo import get_leder_org_units
from sd_managerscript.mo import get_manager_level


@pytest.mark.integration_test
async def test_get_leder_org_units(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
) -> None:
    """
    We are testing this scenario:

        Root
        ├── Department A (led-adm)
        │   └── Team A1_leder
        ├── Department B
        │   └── Team B1_leder
        ├── Department C
        └── Department D
            └── Ø_Team D1_leder

    Explanation:
    - The "led-adm" branch (Department A) contains a child unit named `Team A1_leder`.
    - The "regular" branch (Department B) contains a child unit named `Team B1_leder`.
    - Department C exists under Root but has no child leder-unit.
    - Department D contains a child unit with a name starting with `Ø_`, which should be excluded.

    Purpose:
    - Verify that the query correctly identifies leder org units in mixed hierarchies.
    - Ensure that units starting with `Ø_` are properly excluded.
    - Confirm that both led-adm and regular branches with leder children are handled.
    """

    # Create org-tree
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )

    root = (
        await graphql_client._testing__create_org_unit(
            name="Root",
            parent=None,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_a_led_adm = (
        await graphql_client._testing__create_org_unit(
            name="Department A led-adm",
            parent=root,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_b = (
        await graphql_client._testing__create_org_unit(
            name="Department B",
            parent=root,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_a1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team A1_leder",
            parent=department_a_led_adm,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_b1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team B1_leder",
            parent=department_b,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_c = (
        await graphql_client._testing__create_org_unit(
            name="Department C",
            parent=root,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid
    department_d = (
        await graphql_client._testing__create_org_unit(
            name="Department D",
            parent=root,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid
    team_d1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Ø_Team D1_leder",
            parent=department_d,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    # Create employees
    anders_and = (
        await graphql_client._testing__create_employee(
            first_name="Anders",
            last_name="And",
        )
    ).uuid
    fedtmule = (
        await graphql_client._testing__create_employee(
            first_name="Fedt",
            last_name="mule",
        )
    ).uuid
    joakim = (
        await graphql_client._testing__create_employee(
            first_name="Joakim",
            last_name="von And",
        )
    ).uuid
    fætter_højben = (
        await graphql_client._testing__create_employee(
            first_name="Fætter",
            last_name="Højben",
        )
    ).uuid

    # Create associations
    association_type_uuid = (
        (await graphql_client._testing__get_association_type()).objects[0].uuid
    )

    await graphql_client._testing__create_association(
        team_a1_leder, anders_and, association_type_uuid
    )
    await graphql_client._testing__create_association(
        team_b1_leder, fedtmule, association_type_uuid
    )
    await graphql_client._testing__create_association(
        department_c, joakim, association_type_uuid
    )
    await graphql_client._testing__create_association(
        team_d1_leder, fætter_højben, association_type_uuid
    )

    leder_units = await get_leder_org_units(graphql_client)

    returned_units = {ou.uuid for ou in leder_units}

    assert returned_units == {team_a1_leder, team_b1_leder}
    assert all(
        ou.name.endswith("_leder") and not ou.name.startswith("Ø_")
        for ou in leder_units
    )


@pytest.mark.integration_test
async def test_get_manager_level(
    test_client: AsyncClient, graphql_client: GraphQLClient, settings: _Settings
) -> None:
    """
    Explanation:
    - Each department is assigned a different `org_unit_level`.
    - The test verifies that `get_manager_level` correctly maps each org unit
    to the expected manager level according to the configured `MANAGER_LEVEL_MAPPING`.

    Purpose:
    - Ensure that manager levels are correctly resolved for org units with different levels.
    - Validate that the settings-based mapping is applied properly for all org units.
    """
    # Create org-tree
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )

    org_unit_levels = (await graphql_client._testing__get_org_unit_level()).objects

    org_units = [
        await graphql_client._testing__create_org_unit(
            name="Department A",
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_levels[0].uuid,
        ),
        await graphql_client._testing__create_org_unit(
            name="Department B",
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_levels[1].uuid,
        ),
        await graphql_client._testing__create_org_unit(
            name="Department C",
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_levels[2].uuid,
        ),
        await graphql_client._testing__create_org_unit(
            name="Department D",
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_levels[3].uuid,
        ),
    ]
    for org_unit in org_units:
        manager_level = await get_manager_level(graphql_client, settings, org_unit.uuid)

        org_unit_level_user_key = org_unit.current.org_unit_level.user_key  # type: ignore
        expected_user_key = settings.manager_level_mapping[org_unit_level_user_key]

        expected_manager_level_uuid = (
            (
                await graphql_client._testing__get_manager_level_by_user_key(
                    expected_user_key
                )
            )
            .objects[0]
            .uuid
        )

        assert manager_level == expected_manager_level_uuid


@pytest.mark.integration_test
async def test_build_manager_mutation(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    settings: _Settings,
) -> None:
    """
    We are testing the `build_manager_mutation` function:

    Scenario:
        - A small org tree with two departments, each with one employee.
        - We pass these (org_unit, employee) pairs to `build_manager_mutation`.

    Purpose:
    - Ensure that the mutation correctly constructs `ManagerCreateInput` objects.
    - Validate that the correct `manager_level` is retrieved for each org unit.
    - Confirm that the responsibility, manager type, and validity dates are correctly applied.
    """

    # Create org-tree
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )
    org_unit_levels = (await graphql_client._testing__get_org_unit_level()).objects

    department_a = (
        await graphql_client._testing__create_org_unit(
            name="Department A",
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_levels[0].uuid,
        )
    ).uuid
    department_b = (
        await graphql_client._testing__create_org_unit(
            name="Department B",
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_levels[1].uuid,
        )
    ).uuid

    # Create employees
    alice = (
        await graphql_client._testing__create_employee(
            first_name="Alice", last_name="A"
        )
    ).uuid
    bob = (
        await graphql_client._testing__create_employee(first_name="Bob", last_name="B")
    ).uuid

    # Prepare to_create set
    to_create = {(department_a, alice), (department_b, bob)}

    # Call build_manager_mutation
    mutations = await build_manager_mutation(graphql_client, settings, to_create)  # type: ignore

    # Validate
    today = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)

    expected_levels = {}
    for org_unit_uuid, org_unit_level in [
        (department_a, org_unit_levels[0]),
        (department_b, org_unit_levels[1]),
    ]:
        manager_level_user_key = settings.manager_level_mapping[
            org_unit_level.current.user_key  # type: ignore
        ]
        manager_level_uuid = (
            (
                await graphql_client._testing__get_manager_level_by_user_key(
                    manager_level_user_key
                )
            )
            .objects[0]
            .uuid
        )
        expected_levels[org_unit_uuid] = manager_level_uuid

    assert len(mutations) == 2
    for m in mutations:
        assert m.org_unit in expected_levels
        assert m.manager_level == expected_levels[m.org_unit]
        assert m.person in {alice, bob}
        assert m.responsibility == [settings.responsibility_uuid]
        assert m.manager_type == settings.manager_type_uuid
        assert m.validity.from_ == today
        assert m.validity.to is None
