# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime

import pytest
from freezegun import freeze_time
from httpx import AsyncClient

from sd_managerscript.autogenerated_graphql_client import GraphQLClient
from sd_managerscript.config import ManagerSyncSettings
from sd_managerscript.manager_sync import reconcile_leder_managers


@pytest.mark.integration_test
@freeze_time("2020-01-01")
async def test_reconcile_leder_managers(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    settings: ManagerSyncSettings,
) -> None:
    """
    Integration test for `reconcile_leder_managers`.

    Org tree:

        Root
        ├── Department A (led-adm)
        │   └── Team A1_leder
        ├── Department B
        │   └── Team B1_leder
        ├── Department C
        ├── Department D
        │   └── Ø_Team D1_leder
        └── Department E
            └── Team E1_leder

    Association tiebreaker scenarios per _leder unit:

    Team A1_leder (parent: Dept A led-adm):
      Same employee, multiple associations — to=None beats having an end date:
        emp1: assoc (from=2016-05-05, to=None)    ← kept
        emp1: assoc (from=2010-01-01, to=2030-01-01) ← terminated
      Different employees — employee with latest engagement `from` in parent wins:
        emp5: assoc (to=None) ← terminated (engagement from=2015-01-01 < emp1's 2020-01-01)

    Team B1_leder (parent: Dept B):
      Same employee, both to=None — latest `from` date wins:
        emp2: assoc (to=None, from=2020-01-01) ← kept
        emp2: assoc (to=None, from=2016-05-05) ← terminated
      Different employees — no engagement in parent eliminates employee:
        emp6: assoc (to=None) ← terminated (no engagement in Dept B)

    Team E1_leder (parent: Dept E):
      Same employee, both have end dates — latest end date wins:
        emp7: assoc (from=2010-01-01, to=2030-01-01) ← kept
        emp7: assoc (from=2010-01-01, to=2025-01-01) ← terminated

    Department C: no _leder unit, emp3 associated here → no manager created.

    Ø_Team D1_leder: excluded by Ø_ prefix, emp4 has existing manager → manager terminated.

    Expected outcome:
    - Managers created: 4 (Dept A led-adm, Root, Dept B, Dept E)
    - Managers terminated: 1 (emp4 in Ø_Team D1_leder)
    - Associations terminated: 5
    """

    # Create org-tree
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )

    org_unit_level = (
        (await graphql_client._testing__get_org_unit_level()).objects[0].uuid
    )

    root = (
        await graphql_client._testing__create_org_unit(
            name="Root",
            parent=None,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_a_led_adm = (
        await graphql_client._testing__create_org_unit(
            name="Department A led-adm",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_b = (
        await graphql_client._testing__create_org_unit(
            name="Department B",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    team_a1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team A1_leder",
            parent=department_a_led_adm,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    team_b1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team B1_leder",
            parent=department_b,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_c = (
        await graphql_client._testing__create_org_unit(
            name="Department C",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid
    department_d = (
        await graphql_client._testing__create_org_unit(
            name="Department D",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid
    team_d1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Ø_Team D1_leder",
            parent=department_d,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    department_e = (
        await graphql_client._testing__create_org_unit(
            name="Department E",
            parent=root,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid
    team_e1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team E1_leder",
            parent=department_e,
            org_unit_type=org_unit_type_uuid,
            org_unit_level=org_unit_level,
        )
    ).uuid

    # Create employees
    emp1 = (await graphql_client._testing__create_employee("Emp", "One")).uuid
    emp2 = (await graphql_client._testing__create_employee("Emp", "Two")).uuid
    emp3 = (await graphql_client._testing__create_employee("Emp", "Three")).uuid
    emp4 = (await graphql_client._testing__create_employee("Emp", "Four")).uuid
    emp5 = (await graphql_client._testing__create_employee("Emp", "Five")).uuid
    emp6 = (await graphql_client._testing__create_employee("Emp", "Six")).uuid
    emp7 = (await graphql_client._testing__create_employee("Emp", "Seven")).uuid

    # Create associations
    association_type_uuid = (
        (await graphql_client._testing__get_association_type()).objects[0].uuid
    )

    # --- Team A1_leder associations ---
    # Open-ended (default from=2016-05-05) beats having an end date
    await graphql_client._testing__create_association(
        team_a1_leder, emp1, association_type_uuid
    )
    emp1_old_assoc = (
        await graphql_client._testing__create_association(
            team_a1_leder,
            emp1,
            association_type_uuid,
            from_=datetime(2010, 1, 1),
            to=datetime(2030, 1, 1),
        )
    ).uuid
    # emp5 loses to emp1 (older engagement from in parent)
    emp5_assoc = (
        await graphql_client._testing__create_association(
            team_a1_leder, emp5, association_type_uuid
        )
    ).uuid

    # --- Team B1_leder associations ---
    # Both to=None, latest `from` wins (2020 > default 2016)

    await graphql_client._testing__create_association(
        team_b1_leder,
        emp2,
        association_type_uuid,
        from_=datetime(2020, 1, 1),
    )
    emp2_old_assoc = (
        await graphql_client._testing__create_association(
            team_b1_leder, emp2, association_type_uuid
        )
    ).uuid
    # emp6 has no engagement in parent → eliminated
    emp6_assoc = (
        await graphql_client._testing__create_association(
            team_b1_leder, emp6, association_type_uuid
        )
    ).uuid

    # --- Team E1_leder associations ---
    # Both have end dates, latest end date wins (2030 > 2025)
    await graphql_client._testing__create_association(
        team_e1_leder,
        emp7,
        association_type_uuid,
        from_=datetime(2010, 1, 1),
        to=datetime(2030, 1, 1),
    )
    emp7_old_assoc = (
        await graphql_client._testing__create_association(
            team_e1_leder,
            emp7,
            association_type_uuid,
            from_=datetime(2010, 1, 1),
            to=datetime(2025, 1, 1),
        )
    ).uuid

    # --- Other associations (not in _leder units) ---
    await graphql_client._testing__create_association(
        department_c, emp3, association_type_uuid
    )
    await graphql_client._testing__create_association(
        team_d1_leder, emp4, association_type_uuid
    )

    engagement_type = (
        (await graphql_client._testing__get_engagement_type()).objects[0].uuid
    )

    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )

    # emp1 engagement in Dept A led-adm (from=2020-01-01, beats emp5's 2015-01-01)
    await graphql_client._testing__create_engagement(
        department_a_led_adm,
        emp1,
        engagement_type,
        job_function.uuid,
        from_=datetime(2020, 1, 1),
    )
    # emp5 engagement in Dept A led-adm (from=2015-01-01, loses to emp1)
    await graphql_client._testing__create_engagement(
        department_a_led_adm,
        emp5,
        engagement_type,
        job_function.uuid,
        from_=datetime(2015, 1, 1),
    )

    await graphql_client._testing__create_engagement(
        department_b,
        emp2,
        engagement_type,
        job_function.uuid,
    )
    # emp6: intentionally NO engagement in Dept B → eliminated by Layer 2

    await graphql_client._testing__create_engagement(
        department_c,
        emp3,
        engagement_type,
        job_function.uuid,
    )

    await graphql_client._testing__create_engagement(
        department_d,
        emp4,
        engagement_type,
        job_function.uuid,
    )

    await graphql_client._testing__create_engagement(
        department_e,
        emp7,
        engagement_type,
        job_function.uuid,
    )

    # Create manager for emp4 in Ø_-org
    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid

    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )
    await graphql_client._testing__create_manager(
        team_d1_leder, emp4, manager_level, manager_type, responsibility
    )

    result = await reconcile_leder_managers(graphql_client, settings)
    to_create = result["Manager created"]
    created_pairs = {(m.org_unit, m.person) for m in to_create}

    to_terminate = result["Managers terminated"]
    terminated_pairs = {(ou, emp) for (ou, emp), _ in to_terminate}

    associations_terminated = set(result["Associations terminated"])

    # Assert managers created
    assert created_pairs == {
        (department_a_led_adm, emp1),  # led-adm parent
        (root, emp1),  # led-adm grandparent
        (department_b, emp2),
        (department_e, emp7),
    }

    # Assert managers terminated (Ø_ prefix exclusion)
    assert terminated_pairs == {(team_d1_leder, emp4)}

    # Assert associations terminated
    assert associations_terminated == {
        emp1_old_assoc,  # had end date, lost to to=None
        emp5_assoc,  # older engagement from in parent
        emp2_old_assoc,  # older from date, both to=None
        emp6_assoc,  # no engagement in parent
        emp7_old_assoc,  # earlier end date
    }
