# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from datetime import timedelta

import pytest
from httpx import AsyncClient
from more_itertools import one

from sd_managerscript.autogenerated_graphql_client import GraphQLClient
from sd_managerscript.filters import compute_expected_managers
from sd_managerscript.filters import filter_org_unit_associations


@pytest.mark.integration_test
async def test_filter_org_unit_associations(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
) -> None:
    """
    We are testing `filter_org_unit_associations`:

    Scenario:
        - A single leder org unit with multiple employee associations.
        - Associations have different validity `from` dates.
        - The association with the latest valid `from` date should be kept.
        - All other associations should be marked for termination.
        - Also verify behavior when there are no associations.

    Purpose:
    - Ensure that only the latest valid association is kept.
    - Verify that redundant associations are marked for termination.
    - Confirm correct behavior when there are no associations.
    """

    # Create org unit
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )
    department_a = (
        await graphql_client._testing__create_org_unit(
            name="Department A",
            parent=None,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_a_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team A_leder",
            parent=department_a,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_b = (
        await graphql_client._testing__create_org_unit(
            name="Department B",
            parent=None,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_b_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team B_leder",
            parent=department_b,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_c = (
        await graphql_client._testing__create_org_unit(
            name="Department C",
            parent=None,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_c_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team C_leder",
            parent=department_c,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    # Create employees
    emp1 = (await graphql_client._testing__create_employee("Emp", "One")).uuid
    emp2 = (await graphql_client._testing__create_employee("Emp", "Two")).uuid
    emp3 = (await graphql_client._testing__create_employee("Emp", "Three")).uuid

    now = datetime.now()
    # Create associations with different from-dates
    assoc_type_uuid = (
        (await graphql_client._testing__get_association_type()).objects[0].uuid
    )
    # Associations for Team A_leder
    assoc_a1 = (
        await graphql_client._testing__create_association(
            team_a_leder, emp1, assoc_type_uuid
        )
    ).uuid
    assoc_a2 = (
        await graphql_client._testing__create_association(
            team_a_leder, emp2, assoc_type_uuid
        )
    ).uuid
    assoc_a3 = (
        await graphql_client._testing__create_association(
            team_a_leder, emp3, assoc_type_uuid
        )
    ).uuid

    # Associations for Team B_leder
    assoc_b1 = (
        await graphql_client._testing__create_association(
            team_b_leder, emp1, assoc_type_uuid
        )
    ).uuid
    assoc_b2 = (
        await graphql_client._testing__create_association(
            team_b_leder, emp2, assoc_type_uuid
        )
    ).uuid
    assoc_b3 = (
        await graphql_client._testing__create_association(
            team_b_leder, emp3, assoc_type_uuid
        )
    ).uuid

    # Associations for Team C_leder
    assoc_c1 = (
        await graphql_client._testing__create_association(
            team_c_leder, emp1, assoc_type_uuid
        )
    ).uuid
    assoc_c2 = (
        await graphql_client._testing__create_association(
            team_c_leder, emp2, assoc_type_uuid
        )
    ).uuid
    assoc_c3 = (
        await graphql_client._testing__create_association(
            team_c_leder, emp3, assoc_type_uuid
        )
    ).uuid

    engagement_type = (
        (await graphql_client._testing__get_engagement_type()).objects[0].uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )

    # Engagements for Department A
    await graphql_client._testing__create_engagement(
        department_a,
        emp1,
        engagement_type,
        job_function.uuid,
        from_=(now - timedelta(days=1095)),
    )
    await graphql_client._testing__create_engagement(
        department_a,
        emp2,
        engagement_type,
        job_function.uuid,
        from_=(now - timedelta(days=365)),
    )
    await graphql_client._testing__create_engagement(
        department_a,
        emp3,
        engagement_type,
        job_function.uuid,
        from_=(now - timedelta(days=730)),
    )

    # Engagements for Department B
    await graphql_client._testing__create_engagement(
        department_b,
        emp1,
        engagement_type,
        job_function.uuid,
        from_=(now - timedelta(days=365)),
        to=(now + timedelta(days=100)),
    )
    await graphql_client._testing__create_engagement(
        department_b,
        emp2,
        engagement_type,
        job_function.uuid,
        from_=(now - timedelta(days=2)),
        to=(now + timedelta(days=5)),
    )
    await graphql_client._testing__create_engagement(
        department_b,
        emp3,
        engagement_type,
        job_function.uuid,
        from_=(now + timedelta(days=10)),
    )

    # Leder-unit + expected result
    leder_units = [
        (team_a_leder, [assoc_a2], {assoc_a1, assoc_a3}),
        (team_b_leder, [assoc_b2], {assoc_b1, assoc_b3}),
        (team_c_leder, [], {assoc_c1, assoc_c2, assoc_c3}),
    ]

    for leder_unit, expected_keep, expected_terminate in leder_units:
        # Fetch the org_unit with associations included
        data = await graphql_client._testing__get_leder_org_unit_associations(
            leder_unit
        )
        org_unit = one(one(data.objects).validities)

        reconciled_unit, to_terminate = await filter_org_unit_associations(
            graphql_client,
            org_unit,  # type: ignore
        )

        kept_uuids = [assoc.uuid for assoc in reconciled_unit.associations]

        assert kept_uuids == expected_keep
        assert set(to_terminate) == expected_terminate


@pytest.mark.integration_test
async def test_compute_expected_managers(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
) -> None:
    """
    We are testing this scenario:

        Root
        ├── Department A (led-adm)
        │   └── Team A1_leder  → emp1 association
        └── Department B
            └── Team B1_leder  → emp2 association

    Expected behavior:
    - emp1 should yield managers on Department A led-adm AND Root (due to led-adm rule).
    - emp2 should yield manager only on Department B.
    """

    # Create org-tree
    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )

    root = (
        await graphql_client._testing__create_org_unit(
            name="Root",
            parent=None,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_a_led_adm = (
        await graphql_client._testing__create_org_unit(
            name="Department A led-adm",
            parent=root,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_a1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team A1_leder",
            parent=department_a_led_adm,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    department_b = (
        await graphql_client._testing__create_org_unit(
            name="Department B",
            parent=root,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_b1_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team B1_leder",
            parent=department_b,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    # Create employees
    emp1 = (await graphql_client._testing__create_employee("Emp", "One")).uuid
    emp2 = (await graphql_client._testing__create_employee("Emp", "Two")).uuid

    # Create associations
    association_type_uuid = (
        (await graphql_client._testing__get_association_type()).objects[0].uuid
    )

    await graphql_client._testing__create_association(
        team_a1_leder, emp1, association_type_uuid
    )
    await graphql_client._testing__create_association(
        team_b1_leder, emp2, association_type_uuid
    )

    engagement_type = (
        (await graphql_client._testing__get_engagement_type()).objects[0].uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )

    # Engagements for Department A
    await graphql_client._testing__create_engagement(
        department_a_led_adm,
        emp1,
        engagement_type,
        job_function.uuid,
    )
    await graphql_client._testing__create_engagement(
        department_b,
        emp2,
        engagement_type,
        job_function.uuid,
    )

    leder_units = [team_a1_leder, team_b1_leder]
    filtered_units = []
    for leder_unit in leder_units:
        data = await graphql_client._testing__get_leder_org_unit_associations(
            leder_unit
        )
        org_unit = one(one(data.objects).validities)
        filtered_units.append(org_unit)

    result = await compute_expected_managers(filtered_units)  # type: ignore

    # Assert result is 2 managers for emp1 and 1 for emp2
    assert result == {(department_a_led_adm, emp1), (root, emp1), (department_b, emp2)}


@pytest.mark.integration_test
async def test_filter_same_employee_multiple_associations(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
) -> None:
    """
    Regression test: when the same employee has multiple open-ended associations
    (all with to=None), the one with the newest 'from' date should win.

    Scenario:
        Department Y
        └── Team Y_leder
                ├── association 1 → emp1 (from=90 days ago, to=None)
                └── association 2 → emp1 (from=10 days ago, to=None)  ← should win

    Expected: assoc with latest from date is kept, the other is terminated.
    """

    org_unit_type_uuid = (
        (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    )

    department_y = (
        await graphql_client._testing__create_org_unit(
            name="Department Y",
            parent=None,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    team_y_leder = (
        await graphql_client._testing__create_org_unit(
            name="Team Y_leder",
            parent=department_y,
            org_unit_type=org_unit_type_uuid,
        )
    ).uuid

    emp1 = (await graphql_client._testing__create_employee("Emp", "Tiebreak")).uuid

    assoc_type_uuid = (
        (await graphql_client._testing__get_association_type()).objects[0].uuid
    )

    now = datetime.now()

    # One with an end date, one open-ended (to=None), and one open-ended with newer from.
    # The open-ended with the newest from date should win.
    assoc_with_end = (
        await graphql_client._testing__create_association(
            team_y_leder,
            emp1,
            assoc_type_uuid,
            from_=(now - timedelta(days=90)),
            to=(now + timedelta(days=365)),
        )
    ).uuid
    assoc_open_old_from = (
        await graphql_client._testing__create_association(
            team_y_leder,
            emp1,
            assoc_type_uuid,
            from_=(now - timedelta(days=60)),
        )
    ).uuid
    assoc_open_new_from = (
        await graphql_client._testing__create_association(
            team_y_leder,
            emp1,
            assoc_type_uuid,
            from_=(now - timedelta(days=10)),
        )
    ).uuid

    engagement_type = (
        (await graphql_client._testing__get_engagement_type()).objects[0].uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )

    await graphql_client._testing__create_engagement(
        department_y,
        emp1,
        engagement_type,
        job_function.uuid,
    )

    data = await graphql_client._testing__get_leder_org_unit_associations(team_y_leder)
    org_unit = one(one(data.objects).validities)

    # This should NOT raise ConflictingManagers
    reconciled_unit, to_terminate = await filter_org_unit_associations(
        graphql_client,
        org_unit,  # type: ignore
    )

    # The open-ended association with the newest from date should win:
    # 1. open-ended (to=None) beats having an end date
    # 2. newest from date breaks the tie between the two open-ended ones
    assert len(reconciled_unit.associations) == 1
    assert len(to_terminate) == 2
    assert reconciled_unit.associations[0].uuid == assoc_open_new_from
    assert set(to_terminate) == {assoc_with_end, assoc_open_old_from}
