# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context

from .autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from .config import ManagerSyncSettings as _Settings

Settings = Annotated[_Settings, Depends(from_user_context("settings"))]
GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]
