# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from datetime import timedelta
from uuid import UUID

import structlog

from . import depends
from .autogenerated_graphql_client.input_types import ManagerTerminateInput
from .autogenerated_graphql_client.leder_org_units import (
    LederOrgUnitsOrgUnitsObjectsValidities,
)
from .filters import compute_expected_managers
from .filters import filter_org_unit_associations
from .mo import build_manager_mutation
from .mo import get_leder_org_units

logger = structlog.get_logger()


async def reconcile_leder_managers(
    mo: depends.GraphQLClient, settings: depends.Settings
):
    """
    Main entrypoint: reconciles all _leder managers.
    - Fetch all _leder org units with associations.
    - Filter to only valid managers based on active engagement in parent (handles led-adm).
    - Determine which managers need creation or termination.
    """
    # Step 1: Fetch and parse _leder units
    leder_units = await get_leder_org_units(mo)
    logger.info(f"Fetched {len(leder_units)} _leder units")

    # Step 2: Reconcile each unit and collect redundant associations
    associations_to_terminate: list[UUID] = []
    reconciled_units: list[LederOrgUnitsOrgUnitsObjectsValidities] = []

    for ou in leder_units:
        reconciled, assoc_to_terminate = await filter_org_unit_associations(mo, ou)
        reconciled_units.append(reconciled)
        associations_to_terminate.extend(assoc_to_terminate)

    # Step 3: Build the sets of managers that should exist
    managers_should_exist = await compute_expected_managers(reconciled_units)

    # Step 4: Fetch all current managers globally
    current_managers_data = await mo.current_managers()
    current_managers = {
        (
            manager.current.org_unit_uuid,
            manager.current.employee_uuid,
        ): manager.current.uuid
        for manager in current_managers_data.objects
        if manager.current
    }

    # Step 5: Compute managers to create and terminate
    to_create = managers_should_exist - set(current_managers.keys())
    to_terminate: list[tuple[tuple[UUID, UUID | None], UUID]] = [
        (key, manager_uuid)
        for key, manager_uuid in current_managers.items()
        if key not in managers_should_exist
    ]

    logger.info("Managers to create", to_create=len(to_create))
    logger.info("Managers to terminate", to_terminate=len(to_terminate))

    managers_to_create = await build_manager_mutation(mo, settings, to_create)
    # This should result in yesterday in MO, when using UTC
    yesterday = datetime.now().replace(
        hour=0, minute=0, second=0, microsecond=0
    ) - timedelta(days=1)

    # Step 6: Apply changes
    for manager in managers_to_create:
        await mo.create_manager(manager)

    for key, manager_uuid in to_terminate:
        print("Deleting: ", manager_uuid)
        await mo.terminate_manager(
            ManagerTerminateInput(uuid=manager_uuid, to=yesterday)
        )

    return {"Manager created": managers_to_create, "Managers terminated": to_terminate}
