# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from typing import cast

import structlog
from more_itertools import one

from . import depends
from .autogenerated_graphql_client.client import GraphQLClient
from .autogenerated_graphql_client.input_types import ManagerCreateInput
from .autogenerated_graphql_client.input_types import RAValidityInput
from .autogenerated_graphql_client.leder_org_units import (
    LederOrgUnitsOrgUnitsObjectsValidities,
)
from .autogenerated_graphql_client.org_unit_level import (
    OrgUnitLevelOrgUnitsObjectsValiditiesOrgUnitLevel,
)
from .types import EmployeeUUID
from .types import ManagerLevelUUID
from .types import OrgUnitUUID

logger = structlog.get_logger()


async def get_leder_org_units(
    mo: GraphQLClient,
) -> list[LederOrgUnitsOrgUnitsObjectsValidities]:
    """
    Fetch all _leder org units with associations and convert them into LederOrgUnitsOrgUnitsObjectsValidities models.
    """

    data = await mo.leder_org_units()

    return [
        validity
        for ou in data.objects
        for validity in ou.validities
        if (
            validity.associations
            and validity.name.lower().strip().endswith("_leder")
            and not validity.name.lower().strip().startswith("ø_")
        )
    ]


async def get_manager_level(
    mo: GraphQLClient, settings: depends.Settings, org_unit_uuid: OrgUnitUUID
) -> ManagerLevelUUID:
    """
    Determines the appropriate manager level for an org unit.

    Rules:
      - Normally, use the unit's org_unit_level
      - Special case: if unit name ends with "led-adm",
        use the parent's org_unit_level

    Returns:
        UUID of correct manager_level
    """
    data = await mo.org_unit_level(org_unit_uuid)
    org_unit = one(one(data.objects).validities)

    org_unit_level = org_unit.org_unit_level

    # Special case for led-adm unit
    if org_unit.name.strip().lower().endswith("led-adm"):
        if not org_unit.parent:
            raise ValueError(f"Led-adm unit {org_unit.uuid} has no parent")
        org_unit_level = cast(
            OrgUnitLevelOrgUnitsObjectsValiditiesOrgUnitLevel,
            org_unit.parent.org_unit_level,
        )

    if not org_unit_level:
        raise ValueError(f"Org unit {org_unit.uuid} has no org_unit_level")

    org_unit_level_user_key = org_unit_level.user_key

    # Map org_unit_level_uuid → manager_level_uuid
    manager_level_mapping = settings.manager_level_mapping
    if org_unit_level_user_key not in manager_level_mapping:
        raise KeyError(
            f"No manager_level mapping for org_unit_level: {org_unit_level_user_key}"
        )

    manager_level_user_key = manager_level_mapping[org_unit_level_user_key]

    manager_level = await mo.manager_level(manager_level_user_key)
    manager_level_uuid = one(one(manager_level.objects).validities).uuid

    return manager_level_uuid


async def build_manager_mutation(
    mo: GraphQLClient,
    settings: depends.Settings,
    to_create: set[tuple[OrgUnitUUID, EmployeeUUID | None]],
) -> list[ManagerCreateInput]:
    # get 1 date (could possibly be from 2 different dates depending on when the script runs)
    today = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
    return [
        ManagerCreateInput(
            person=employee_uuid,
            responsibility=[settings.responsibility_uuid],
            org_unit=org_unit_uuid,
            manager_level=await get_manager_level(mo, settings, org_unit_uuid),
            manager_type=settings.manager_type_uuid,
            validity=RAValidityInput(**{"from": today, "to": None}),
        )
        for org_unit_uuid, employee_uuid in to_create
    ]
